api:
    route: /faucet
    ssl:
        dircert: /home/me/.faucet/tls
        domain: ""
datadir: /home/me/.faucet
faucet:
    enableevm: true
    enablevocdoni: true
    evmamount: "1"
    evmendpoints: []
    evmnetwork: ""
    evmprivkeys: []
    evmsendconditions:
        balance: "100"
        challenge: false
    vocdonisendconditions:
        balance: "100"
        challenge: false
    vocdoniamount: "100"
    vocdoninetwork: ""
    vocdoniprivkey: ""
logerrorfile: ""
loglevel: info
logoutput: stdout
